version: '3'

services:

  metadata-prod-ui:
    image: db-compose-runtime:latest
    ports:
      - 8002:8000
    env_file:
      - ./.env # Points to the .env file in the same directory
    volumes:
      - ./models.py:/app/src/models.py
      - ./admin.py:/app/src/admin.py
      - ./migrations:/app/src/migrations
