branch = "stage"
organization_id = "ginger-society"

[[database]]
db_type = "rdbms"
description = "Identity and authorization db for IAM service"
enable = true
id = "a56e44a9-cfc6-4f69-9b7f-510789b6fa80"
name = "IAM"
port = "5432"
studio_port = "9002"

[[database.links]]
internal = true
label = "Pull Requests"
icon = "FaCodeBranch"
link = "https://github.com/ginger-society/ginger-society-db/pulls"

[[database.links]]
internal = true
label = "Pipelines"
icon = "FaRegPlayCircle"
link = "https://github.com/ginger-society/ginger-society-db/actions"

[[database.links]]
internal = true
label = "Browse Repo"
icon = "FaGithub"
link = "https://github.com/ginger-society/ginger-society-db"

[[database]]
db_type = "rdbms"
description = "Dev portal db for Metadata Service"
enable = true
id = "66bbad42-200f-4b2f-ba0d-9feb1f3edbfa"
name = "metadata"
port = "5433"
studio_port = "8001"

[[database.links]]
internal = true
label = "Pull Requests"
icon = "FaCodeBranch"
link = "https://github.com/ginger-society/metadata-service-db/pulls"

[[database.links]]
internal = true
label = "Pipelines"
icon = "FaRegPlayCircle"
link = "https://github.com/ginger-society/metadata-service-db/actions"

[[database.links]]
internal = true
label = "Browse Repo"
icon = "FaGithub"
link = "https://github.com/ginger-society/metadata-service-db"

[[database]]
db_type = "cache"
description = "cache for IAM and Metadata service"
enable = true
id = "a3f5e631-8225-4ac5-85b9-71ecd107bb6c"
name = "estonia"
port = "6380"
links = []

[[database]]
db_type = "messagequeue"
description = "Rabbit mq based message queue"
enable = true
id = "6a06e876-b40f-472d-be2b-97a2867b88f3"
name = "changi"
port = "5672"
studio_port = "15672"
links = []
