# Generated by Ginger 5.3.4 on 2024-08-04 11:54

from gingerdj.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("src", "0003_delete_test_table"),
    ]

    operations = [
        migrations.RenameField(
            model_name="app",
            old_name="app_url",
            new_name="app_url_dev",
        ),
        migrations.AddField(
            model_name="app",
            name="app_url_prod",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="app",
            name="app_url_stage",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
