# Generated by Ginger 5.3.4 on 2024-08-25 14:38

from ginger.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0005_api_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='api_token',
            name='token_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
