# Generated by Ginger 5.3.4 on 2024-08-25 16:37

from ginger.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0006_api_token_token_str'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api_token',
            name='token_str',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
