# Generated by Ginger 5.3.13 on 2024-10-08 09:50

from gingerdj.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("src", "0008_app_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="app",
            name="tnc_link",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
