# Generated by Ginger 5.3.13 on 2024-10-09 08:43

import gingerdj.db.models.deletion
from gingerdj.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("src", "0009_app_tnc_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="app",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=gingerdj.db.models.deletion.SET_NULL,
                related_name="apps",
                to="src.group",
            ),
        ),
        migrations.AlterField(
            model_name="token",
            name="app",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=gingerdj.db.models.deletion.CASCADE,
                to="src.app",
            ),
        ),
    ]
