# Generated by GingerDJ 6.0.8 on 2024-12-13 08:43

from gingerdj.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0013_delete_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='description',
            field=models.TextField(max_length=2000, null=True),
        ),
    ]
