# Generated by GingerDJ 6.0.8 on 2024-12-13 09:45

from gingerdj.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0014_app_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='auth_redirection_path',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
