# Generated by GingerDJ 6.0.8 on 2024-12-13 15:20

from gingerdj.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0015_app_auth_redirection_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='web_interface',
            field=models.BooleanField(default=True),
        ),
    ]
