# Generated by GingerDJ 6.0.8 on 2025-01-31 05:07

from gingerdj.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0016_app_web_interface'),
    ]

    operations = [
        migrations.CreateModel(
            name='tableexample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.CharField(max_length=300)),
                ('bool1', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'tableexample',
            },
        ),
    ]
