# Generated by GingerDJ 6.0.8 on 2026-04-23 19:22

from gingerdj.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0017_tableexample'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tableexample',
        ),
    ]
