# Generated by Ginger 5.3.4 on 2024-07-22 13:17

from gingerdj.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("src", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="service_type",
            field=models.CharField(
                choices=[("rpcendpoint", "RPCEndpoint"), ("portal", "Portal")],
                default="RPCEndpoint",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="service_envs",
            name="version",
            field=models.CharField(default="0.0.0", max_length=50),
        ),
    ]
