# Generated by Ginger 5.3.4 on 2024-07-24 06:02

from gingerdj.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("src", "0002_service_service_type_service_envs_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="lang",
            field=models.CharField(
                blank=True,
                choices=[("ts", "TS"), ("rust", "Rust"), ("python", "Python")],
                max_length=25,
                null=True,
            ),
        ),
    ]
