# Generated by Ginger 5.3.4 on 2024-07-24 06:20

from gingerdj.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("src", "0003_service_lang"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service_envs",
            name="spec",
            field=models.TextField(max_length=20000),
        ),
    ]
