# Generated by Ginger 5.3.4 on 2024-07-24 06:42

from gingerdj.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("src", "0005_alter_service_lang"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="lang",
            field=models.CharField(
                blank=True,
                choices=[
                    ("typescript", "typescript"),
                    ("rust", "Rust"),
                    ("python", "Python"),
                ],
                max_length=25,
                null=True,
            ),
        ),
    ]
