# Generated by Ginger 5.3.4 on 2024-08-04 09:00

from ginger.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("src", "0006_alter_service_lang"),
    ]

    operations = [
        migrations.CreateModel(
            name="package",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identifier", models.CharField(max_length=100)),
                (
                    "package_type",
                    models.CharField(
                        choices=[("library", "library"), ("executable", "executable")],
                        max_length=50,
                    ),
                ),
                ("lang", models.CharField(max_length=50)),
                ("version", models.CharField(max_length=30)),
            ],
            options={
                "db_table": "package",
            },
        ),
        migrations.RemoveField(
            model_name="service",
            name="lang",
        ),
        migrations.AlterField(
            model_name="service",
            name="service_type",
            field=models.CharField(
                choices=[("portal", "Portal"), ("rpcendpoint", "RPCEndpoint")],
                default="RPCEndpoint",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="service_envs",
            name="spec",
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name="service_envs",
            name="version",
            field=models.CharField(default="0.0.0", max_length=30),
        ),
    ]
