# Generated by Ginger 5.3.4 on 2024-08-04 09:30

from ginger.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0008_service_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='group_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
