# Generated by Ginger 5.3.4 on 2024-08-04 09:41

from ginger.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0009_package_group_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
