# Generated by Ginger 5.3.4 on 2024-08-04 09:47

from ginger.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0010_package_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
