# Generated by Ginger 5.3.4 on 2024-08-04 14:10

from ginger.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0011_package_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='description',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='organization_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='organization_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
