# Generated by Ginger 5.3.4 on 2024-08-04 14:28

from ginger.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0012_package_description_package_organization_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_envs',
            name='spec',
            field=models.TextField(max_length=20000),
        ),
    ]
