# Generated by Ginger 5.3.4 on 2024-08-04 14:32

from ginger.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0013_alter_service_envs_spec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_envs',
            name='spec',
            field=models.TextField(max_length=35000),
        ),
    ]
