# Generated by Ginger 5.3.4 on 2024-08-05 08:26

from ginger.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0014_alter_service_envs_spec'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbschema',
            name='organization_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
