# Generated by Ginger 5.3.4 on 2024-08-13 05:31

from ginger.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0015_dbschema_organization_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='test_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'test_table',
            },
        ),
    ]
