# Generated by Ginger 5.3.4 on 2024-08-13 05:34

from ginger.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0016_test_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='description',
        ),
    ]
