# Generated by Ginger 5.3.4 on 2024-08-13 15:04

from gingerdj.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("src", "0018_delete_test_table_package_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="dependencies_json",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
