# Generated by Ginger 5.3.4 on 2024-08-18 08:42

from gingerdj.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("src", "0019_package_dependencies_json"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="col_one",
            field=models.CharField(
                blank=True,
                choices=[("opt1", "opt1"), ("opt2", "opt2")],
                max_length=40,
                null=True,
            ),
        ),
    ]
