# Generated by Ginger 5.3.4 on 2024-08-19 08:44

from gingerdj.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("src", "0020_service_col_one"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="col_one",
        ),
    ]
