# Generated by Ginger 5.3.4 on 2024-08-19 09:08

from gingerdj.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("src", "0021_remove_service_col_one"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dbschema",
            name="version",
        ),
        migrations.RemoveField(
            model_name="dbschema_branch",
            name="merged",
        ),
        migrations.AddField(
            model_name="dbschema_branch",
            name="version",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
