# Generated by Ginger 5.3.4 on 2024-08-19 10:57

import gingerdj.db.models.deletion
from gingerdj.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("src", "0022_remove_dbschema_version_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="package_env",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.CharField(max_length=50)),
                (
                    "env",
                    models.CharField(
                        choices=[("dev", "dev"), ("stage", "stage"), ("prod", "prod")],
                        max_length=10,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=gingerdj.db.models.deletion.CASCADE,
                        related_name="envs",
                        to="src.package",
                    ),
                ),
            ],
            options={
                "db_table": "package_env",
            },
        ),
    ]
