# Generated by Ginger 5.3.4 on 2024-08-19 11:05

from ginger.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0023_package_env'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='version',
        ),
    ]
