# Generated by Ginger 5.3.4 on 2024-08-19 12:25

from ginger.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0024_remove_package_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbschema_branch',
            name='pipeline_status',
            field=models.CharField(blank=True, choices=[('running', 'running'), ('failed', 'failed'), ('passing', 'passing'), ('dormant', 'dormant')], max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='package_env',
            name='pipeline_status',
            field=models.CharField(blank=True, choices=[('running', 'running'), ('failed', 'failed'), ('passing', 'passing'), ('dormant', 'dormant')], max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='service_envs',
            name='pipeline_status',
            field=models.CharField(blank=True, choices=[('running', 'running'), ('failed', 'failed'), ('passing', 'passing'), ('dormant', 'dormant')], max_length=70, null=True),
        ),
    ]
