# Generated by Ginger 5.3.4 on 2024-08-20 09:26

from gingerdj.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("src", "0026_organization_dbschema_repo_origin_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="blocks_positions",
            field=models.TextField(max_length=40000, null=True),
        ),
        migrations.AddField(
            model_name="package",
            name="demo_col",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
