# Generated by Ginger 5.3.4 on 2024-08-23 11:51

from gingerdj.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("src", "0028_remove_package_demo_col"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
