# Generated by Ginger 5.3.4 on 2024-09-08 12:19

from ginger.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0030_dbschema_db_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbschema',
            name='group_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
