# Generated by Ginger 5.3.4 on 2024-09-08 14:26

from gingerdj.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("src", "0031_alter_dbschema_group_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="cache_schema_id",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
