# Generated by Ginger 5.3.4 on 2024-09-23 11:45

from ginger.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0035_dbschema_quick_links_package_quick_links_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='snapshots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization_id', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'snapshots',
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='infra_repo_origin',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
