# Generated by Ginger 5.3.4 on 2024-10-01 05:44

from ginger.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0036_snapshots_organization_infra_repo_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='message_queue_schema_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
