# Generated by Ginger 5.3.4 on 2024-10-03 10:17

from ginger.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0038_organization_quick_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='version',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
