# Generated by GingerDJ 6.0.8 on 2024-11-15 11:43

from gingerdj.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0039_organization_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_envs',
            name='base_url_ws',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
