name: Build, Push Docker Image, and Restart Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install ginger-apps
      run: bash -c "$(curl -fsSL https://raw.githubusercontent.com/ginger-society/infra-as-code-repo/main/rust-helpers/install-all-clis.sh)"

    - name: Authenticate with ginger-auth
      id: ginger-auth
      run: ginger-auth token-login ${{ secrets.GINGER_TOKEN }}

    - name: Update pipeline to running
      run: ginger-connector update-db-pipeline stage running ginger-society/IAM

    - name: Update pipeline to running
      run: ginger-connector update-db-pipeline stage running ginger-society/metadata

    - name: Migrate for IAM DB
      working-directory: ./IAM
      run: |
        echo "Starting migration for IAM DB"
        docker run \
          -e DB_HOST=${{ secrets.DB_HOST }} \
          -e DB_PORT=${{ secrets.DB_PORT }} \
          -e DB_USERNAME=${{ secrets.DB_USERNAME }} \
          -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
          -e DB_NAME=${{ secrets.DB_NAME_ONE }} \
          -v $(pwd)/models.py:/app/src/models.py \
          -v $(pwd)/admin.py:/app/src/admin.py \
          -v $(pwd)/migrations:/app/src/migrations \
          gingersociety/db-compose-migrator:latest

    - name: Update pipeline to running
      run: ginger-connector update-db-pipeline stage passing ginger-society/IAM

    - name: Migrate for Metadata DB
      working-directory: ./metadata
      run: |
        echo "Starting migration for Metadata DB"
        docker run \
          -e DB_HOST=${{ secrets.DB_HOST }} \
          -e DB_PORT=${{ secrets.DB_PORT }} \
          -e DB_USERNAME=${{ secrets.DB_USERNAME }} \
          -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
          -e DB_NAME=${{ secrets.DB_NAME_TWO }} \
          -v $(pwd)/models.py:/app/src/models.py \
          -v $(pwd)/admin.py:/app/src/admin.py \
          -v $(pwd)/migrations:/app/src/migrations \
          gingersociety/db-compose-migrator:latest

    - name: Update pipeline to running
      run: ginger-connector update-db-pipeline stage passing ginger-society/metadata
