name: Build, Push Docker Image, and Restart Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Migrate for iam db
      run: docker run -v ./IAM/models.py:/app/src/models.py -v ./IAM/admin.py:/app/src/admin.py -v ./IAM/migrations:/app/src/migrations gingersociety/db-compose-migrator:latest
      env:
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_PORT: ${{ secrets.DB_PORT }}
        DB_USERNAME: ${{ secrets.DB_USERNAME }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_NAME: ${{ secrets.DB_NAME_ONE }}

    - name: Run migrations for metadata db
      run: docker run -v ./metadata/models.py:/app/src/models.py -v ./metadata/admin.py:/app/src/admin.py -v ./metadata/migrations:/app/src/migrations gingersociety/db-compose-migrator:latest
      env:
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_PORT: ${{ secrets.DB_PORT }}
        DB_USERNAME: ${{ secrets.DB_USERNAME }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_NAME: ${{ secrets.DB_NAME_TWO }}
    
