name: Build, Push Docker Image, and Restart Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Install ginger-apps
      run: bash -c "$(curl -fsSL https://raw.githubusercontent.com/ginger-society/infra-as-code-repo/main/rust-helpers/install-all-clis.sh)"

    - name: Authenticate with ginger-auth
      id: ginger-auth
      run: ginger-auth token-login ${{ secrets.GINGER_TOKEN }}

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

    - name: Update pipeline to running for Metadata DB
      run: ginger-connector update-db-pipeline stage running ginger-society/metadata

    - name: Build metadata-db runtime image
      working-directory: ./metadata
      run: |
        echo "Building metadata-db runtime image"
        docker buildx build -t gingersociety/metadata-db-runtime . --load

    - name: Push metadata-db runtime image
      run: |
        echo "Pushing metadata-db runtime image to Docker Hub"
        docker push gingersociety/metadata-db-runtime
    
    - name: Update pipeline to passing for Metadata DB
      run: ginger-connector update-db-pipeline stage passing ginger-society/metadata

    - name: Update pipeline to running for IAM DB
      run: ginger-connector update-db-pipeline stage running ginger-society/IAM

    - name: Build IAM-db runtime image
      working-directory: ./IAM
      run: |
        echo "Building iam-db runtime image"
        docker buildx build -t gingersociety/iam-db-runtime . --load

    - name: Push IAM-db runtime image
      run: |
        echo "Pushing iam-db runtime image to Docker Hub"
        docker push gingersociety/iam-db-runtime

    - name: Update pipeline to passing for IAM DB
      run: ginger-connector update-db-pipeline stage passing ginger-society/IAM
